### ISSUE TITLE
slabs appear as full blocks

### ISSUE THREAD

**Issue by eueesuarez** [Enchanted-Games/enchanted-vertical-slabs#12] opened 2024-08-08 12:54 UTC
Hey man don't know if you'll see this as I don't use Minecraft mods alot but if you do I got a weird issue, it's to do with your vertical slabs mod. I had a couple of crashes on my server and reset it and now whenever I place down a vertical slab it comes as a full block sometimes not even the same as the slab and then turns into a half slab when I place another which would turn it into a full block. The problem is though it's not actually a half slab and the game knows that and so wont let me walk into the space that it shows and stutters, it also wont let me walk into the space when its just a half slab appearing as a full block though. Any help would be appreciated, and if you don't know how to fix it that's fine just let me know, thank you.
[https://www.youtube.com/watch?v=U_KJfcvXZJE](url)

Minecraft 1.21
Fabric 0.16.0
Using a GPortal hosted server
Mod List:
Advanced Netherite (Fabric)
AdventureZ
Anvil Never Too Expensive
AppleSkin
BCLib
Better End Cities Better End
Better than Mending
Better Walls
BetterEnd
BetterNether
Bosses of Mass Destruction
Cardinal Components API
Cloth Config API (Fabric/Forge/NeoForge)
Clumps
Controlling
Diamond In The Rough (as in obsidian)
Disenchanter
Dungeons and Taverns
Durability Tooltip
Easy Emerald Tools & More [FABRIC]
Easting Animation [Fabric]
Elytra Slot (Fabric/Forge/Quilt)
Enchanted Vertical Slabs
Fabric API
Fabric Language Kotlin
GeckoLib
Iris Shaders
JourneyMap
JourneyMap Web Map
Just Enough Items (JEI)
MES - Moog's End Structures
MES - Moog's Nether Structures
Mod Menu
More Gems [FABRIC]
Mouse Tweaks
oωo (owo-lib)
Reinforced Chests
Searchables
Shulker Box Tooltip [Fabric/Forge/NeoForge]
Sodium
SuperMartijn642's Config Lib
Text Placeholder API
Trinkets (Fabric)
WorldWeaver
XP Storage
Yeleefff's Enderite

**Comment by Enchanted-Games** [comment] 2024-08-08 13:40
thanks for the mod list, however I can't seem to reproduce this. can you send the latest.log from the server and client? i'm hoping it will have more information about what is going on here

**Comment by Enchanted-Games** [comment] 2024-08-08 14:16
ah i see. i did hear somewhere about an issue with fabric api and blockstates but that could be unrelated. i guess the only thing i can recommend is to make sure all the mods are up to date

**Comment by Enchanted-Games** [comment] 2024-08-12 10:26
I’m going to close this as not planned since this doesn’t seem related to enchanted vertical slabs

**Closed by Enchanted-Games** 2024-08-12 10:26 UTC
Labels: bug, unconfirmed
